[package]
name = "term-emul"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[workspace]
members = ["ui", "raw-mode"]

[dependencies]
nix = "0.17.0"
raw-mode = { path = "./raw-mode" }
ui = { path = "./ui" }
